export const userUrls = {
  LOGIN: 'user/login',
  LOGOUT: 'user/logout',
  IS_LOGGED_IN: 'user/is-logged-in',
  USER: 'user/data',
  TEAM: 'user/team',
  REQUEST_TEAM: 'user/request-team',
  TRAIN_PLAYER: 'user/train-player',
  CHEER_PLAYER: 'user/cheer-player',
  LEADERBOARD: 'user/leaderboard',
  SHARE: 'user/share',
  BOOST: 'user/boost',
  HAS_TEAM: 'user/has-team',
  CHECK_TEAM_NAME: 'user/check-team-name',
  EDIT_TEAM_LOGO: 'user/edit-team-logo',
};
