export const userUrls = {
  LOGIN: 'login',
  LOGOUT: 'logout',
  IS_LOGGED_IN: 'is-logged-in',
  USER: 'user',
  TEAM: 'team',
  CREATE_TEAM: 'create-team',
  TRAIN_PLAYER: 'train-player',
  CHEER_PLAYER: 'cheer-player',
  LEADERBOARD: 'leaderboard',
  SHARE: 'share',
  BOOST: 'boost',
  HAS_TEAM: 'has-team',
  CHECK_TEAM_NAME: 'check-team-name',
};
